### PR TITLE
Build wheels on macos-13

### PR DESCRIPTION
**Pull request by johnwlambert**

### CODE REVIEW

**Comment by ProfFan** [comment]
Note building on 13 will not run on older macs

**Review by varunagrawal — APPROVED** [review]
I am assuming PyPI has a way of matching the ABIs for each mac version so as to install the correct version.

If we have issues, we can re-examine this.

**Comment by varunagrawal** [comment]
**NOTE**: The wheels still have the wrong version information. They still say 4.2a9 instead of 4.2.0. You may want to merge #39 before this PR.

**Review by varunagrawal — CHANGES_REQUESTED** [review]
Actually, I shouldn't approve this since the version name of the wheels is wrong in this PR. :(

**Review by varunagrawal — APPROVED** [review]
Approving now that #39 has been merged.

**Pull request merged**
