### PR TITLE
Release 4.2a4

### PR DESCRIPTION
**Pull request by dellaert**

### CODE REVIEW

**Comment by dellaert** [comment]
@ProfFan could you add 12.0 build here? I guess it's editing the workflow?

**Comment by dellaert** [comment]
@ProfFan don't understand why it's failing. I have replaced all 4.2a3 with 4.2a4 but it still somehow refers to 4.2a3. What did I forget?

**Comment by dellaert** [comment]
Dang, I know! Have to bump version!

**Comment by ProfFan** [comment]
Yes that is correct :)

**Comment by dellaert** [comment]
@ProfFan Did you cancel the build? I had already restarted after bumping

**Comment by dellaert** [comment]
Please don't touch CI here - can't have two people managing this. I will now restart again.

**Comment by dellaert** [comment]
If you are planning something *communicate*. Probably best by email at this point

**Comment by ProfFan** [comment]
Copy that

**Comment by dellaert** [comment]
@ProfFan Mac fails. Could you please look into that?

**Comment by ProfFan** [comment]
Yes

**Comment by ProfFan** [comment]
Seems upstream has fixed the issue, can I push to this branch @dellaert ?

**Comment by dellaert** [comment]
Yep, go for it! I'll test the linux wheels in meantime

**Comment by dellaert** [comment]
OK, Linux wheels are up, but I'll have to wait for you to release gtbook, as otherwise people on Macs will suffer. Send me *and* Junyan *email* when it's done so he can test on Intel mac? After that I'll upload to twine

**Comment by dellaert** [comment]
BTW:
- why only macos-latest ? Seems we should do matrix with both macos-11 and macos-10.15 right?
- Did you clean up intermediate results or is that automatic now?

**Comment by ProfFan** [comment]
It should be automatic

I'll add 10.15 after this builds so you can get the build earlier

**Comment by ProfFan** [comment]
@dellaert Build is complete

**Comment by dellaert** [comment]
Thanks!

**Comment by johnwlambert** [comment]
Beautiful. Thank you for making these @dellaert and @ProfFan

**Comment by dellaert** [comment]
> Beautiful. Thank you for making these @dellaert and @ProfFan

John can you confirm for me that they work on Intel Macs? And tell me your OS version

**Comment by dellaert** [comment]
I downloaded Mac 11 wheels, @ProfFan . Could you add mac 10.5 to the matrix now?

**Review by johnwlambert — APPROVED** [review]
LGTM, let's merge?

**Comment by johnwlambert** [comment]
> 

One of my Intel Macs is on OS 10.15, so I can't use the 11.0 wheel.

**Comment by ProfFan** [comment]
i'll do it tomorrow morning

**Comment by dellaert** [comment]
Same issue for me:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/py38/lib/python3.8/site-packages/gtsam/__init__.py", line 7, in <module>
    from gtsam import gtsam, utils
ImportError: dlopen(/opt/miniconda3/envs/py38/lib/python3.8/site-packages/gtsam/gtsam.cpython-38-darwin.so, 2): Library not loaded: @loader_path/../../../gtsam.dylibs/libgtsam.4.2.0.dylib
  Referenced from: /opt/miniconda3/envs/py38/lib/python3.8/site-packages/gtsam/gtsam.cpython-38-darwin.so
  Reason: image not found
>>> 
```

**Comment by dellaert** [comment]
And:
```
(py38) MetalZero-2:Downloads dellaert$ pip debug —verbose
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 21.2.4 from /opt/miniconda3/envs/py38/lib/python3.8/site-packages/pip (python 3.8)
sys.version: 3.8.12 (default, Oct 12 2021, 06:23:56) 
[Clang 10.0.0 ]
sys.executable: /opt/miniconda3/envs/py38/bin/python
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: UTF-8
sys.platform: darwin
sys.implementation:
  name: cpython
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): /opt/miniconda3/envs/py38/lib/python3.8/site-packages/pip/_vendor/certifi/cacert.pem
pip._vendor.DEBUNDLED: False
vendored library versions:
  appdirs==1.4.4
  CacheControl==0.12.6
  colorama==0.4.4
  distlib==0.3.2
  distro==1.5.0 (Unable to locate actual module version, using vendor.txt specified version)
  html5lib==1.1
  msgpack==1.0.2 (Unable to locate actual module version, using vendor.txt specified version)
  packaging==21.0
  pep517==0.11.0
  progress==1.5
  pyparsing==2.4.7
  requests==2.26.0
  certifi==2021.05.30
  chardet==4.0.0
  idna==3.2
  urllib3==1.26.6
  resolvelib==0.7.1
  setuptools==44.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.16.0
  tenacity==8.0.1 (Unable to locate actual module version, using vendor.txt specified version)
  tomli==1.0.3
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 1493
  cp38-cp38-macosx_10_16_x86_64
  cp38-cp38-macosx_10_16_intel
  cp38-cp38-macosx_10_16_fat64
  cp38-cp38-macosx_10_16_fat32
  cp38-cp38-macosx_10_16_universal2
  cp38-cp38-macosx_10_16_universal
  cp38-cp38-macosx_10_15_x86_64
  cp38-cp38-macosx_10_15_intel
  cp38-cp38-macosx_10_15_fat64
  cp38-cp38-macosx_10_15_fat32
  ...
  [First 10 tags shown. Pass --verbose to show all.]
```

**Comment by ProfFan** [comment]
script did not work properly, I'll manually patch and send to you through email

**Comment by dellaert** [comment]
> script did not work properly, I'll manually patch and send to you through email

I'd prefer if we can fix the flow. Is that not possible?

**Comment by ProfFan** [comment]
I'll fix it soon

**Pull request merged**
