### PR TITLE
Fix Wheels build

### PR DESCRIPTION
**Pull request by varunagrawal**
I updated the `wrap` CMake macros to not do a `REQUIRED` when trying to locate the Python cmake info. This will allow CMake to run on the docker image used for building the wheels.

### CODE REVIEW

**Comment by johnwlambert** [comment]
Thanks for updating that documentation, that helps. Would you mind also explaining in the PR description how this fixes the bug/ why the old was led to a crashed build?

**Comment by johnwlambert** [comment]
is the distutils method more reliable than
```bash
PYTHON_INCLUDE_DIR=$( find -L ${PYBIN}/../include/ -name Python.h -exec dirname {} \; ), 
PYTHON_LIBRARY:FILEPATH=${PYTHON_LIBRARY}; ec=$?
```

**Comment by varunagrawal** [comment]
> is the distutils method more reliable than
> 
> ```shell
> PYTHON_INCLUDE_DIR=$( find -L ${PYBIN}/../include/ -name Python.h -exec dirname {} \; ), 
> PYTHON_LIBRARY:FILEPATH=${PYTHON_LIBRARY}; ec=$?
> ```

Yes because we are asking the interpreter directly for those values rather than looking for a file named `Python.h` in the directory tree (which is also less efficient).

**Comment by varunagrawal** [comment]
@ProfFan @johnwlambert I dropped support for Python 3.5 since it reached its EOL on 09/20/2020.

**Comment by johnwlambert** [comment]
> @ProfFan @johnwlambert I dropped support for Python 3.5 since it reached its EOL on 09/20/2020.

**Comment by johnwlambert** [comment]
Accidentally closed this. Sounds good about deprecating python 3.5.

**Comment by varunagrawal** [comment]
Okay looks like this build is going to succeed (barring anything crazy) :tada:

**Comment by ProfFan** [comment]
@varunagrawal Is there anything preventing the 3.5 build? If not we should probably keep it.

**Comment by varunagrawal** [comment]
Yeah I set the minimum python version in gtwrap to be 3.6, so it won't install in the 3.5 version.

**Comment by ProfFan** [comment]
Maybe we should set that to be 3.5, I think there are still many devices on 3.5 (esp. robot controllers) that are stuck on 16.04.

**Comment by varunagrawal** [comment]
That should be the onus on them, but alright, I'll add back the support.

**Comment by johnwlambert** [comment]
any idea why linux python3.8 is getting skipped in CI?

**Comment by varunagrawal** [comment]
I'll look at it again once the CI finishes.

**Comment by varunagrawal** [comment]
Looks like the issue was just Actions timing out.

**Pull request merged**
