### PR TITLE
add-macos-10-builder

### PR DESCRIPTION
**Pull request by johnwlambert**

### CODE REVIEW

**Comment by dellaert** [comment]
Thank you !!!!

**Comment by dellaert** [comment]
@johnwlambert were you able to test this on your 10.15 install? I tried on two old macs and got this weird error on both:
```
(py38) MetalZero-2:~/Downloads>python
Python 3.8.12 (default, Oct 12 2021, 06:23:56) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gtsam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/py38/lib/python3.8/site-packages/gtsam/__init__.py", line 7, in <module>
    from gtsam import gtsam, utils
ImportError: dlopen(/opt/miniconda3/envs/py38/lib/python3.8/site-packages/gtsam/gtsam.cpython-38-darwin.so, 2): Library not loaded: @loader_path/../../../gtsam.dylibs/libgtsam.4.2.0.dylib
  Referenced from: /opt/miniconda3/envs/py38/lib/python3.8/site-packages/gtsam/gtsam.cpython-38-darwin.so
  Reason: image not found
>>> 
```

admittedly, both macs are basically clones from a long chain of macs, and might have the same issues.

**Comment by johnwlambert** [comment]
> @johnwlambert were you able to test this on your 10.15 install? I tried on two old macs and got this weird error on both:
> 
> ```
> (py38) MetalZero-2:~/Downloads>python
> Python 3.8.12 (default, Oct 12 2021, 06:23:56) 
> [Clang 10.0.0 ] :: Anaconda, Inc. on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import gtsam
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/opt/miniconda3/envs/py38/lib/python3.8/site-packages/gtsam/__init__.py", line 7, in <module>
>     from gtsam import gtsam, utils
> ImportError: dlopen(/opt/miniconda3/envs/py38/lib/python3.8/site-packages/gtsam/gtsam.cpython-38-darwin.so, 2): Library not loaded: @loader_path/../../../gtsam.dylibs/libgtsam.4.2.0.dylib
>   Referenced from: /opt/miniconda3/envs/py38/lib/python3.8/site-packages/gtsam/gtsam.cpython-38-darwin.so
>   Reason: image not found
> >>> 
> ```
> 
> admittedly, both macs are basically clones from a long chain of macs, and might have the same issues.

I'm getting the same error @dellaert, haven't seen this before. Something is wrong.

**Comment by ProfFan** [comment]
Could you merge #26 first @dellaert ?

**Comment by ProfFan** [comment]
Thanks @johnwlambert !

**Pull request merged**
