### PR TITLE
Adding 10.15 builder

### PR DESCRIPTION
**Pull request by ProfFan**

### CODE REVIEW

**Comment by johnwlambert** [comment]
Thanks for the PR @ProfFan. I think we can make this change in just 2 lines, by following what I do here: https://github.com/borglab/gtsam-manylinux-build/pull/23/files

**Comment by dellaert** [comment]
2 questions:
- Do these wheels have to be "re-located" as well?
- did you clean up the intermediate results so we just get the wheel? (in all mac versions)

**Comment by ProfFan** [comment]
@johnwlambert Thanks for the suggestion!

@dellaert No I haven't, this PR is just me trying to get a quick build.

**Comment by dellaert** [comment]
@ProfFan , Is there anything else to be done? Can we merge this PR so master consistently build MacOS-15 wheels without having to ask you each time?

**Comment by johnwlambert** [comment]
> @ProfFan , Is there anything else to be done? Can we merge this PR so master consistently build MacOS-15 wheels without having to ask you each time?

Hi Frank, I believe we merged the macOS-10 wheel builder into master already here: https://github.com/borglab/gtsam-manylinux-build/pull/27

**Pull request closed without merging**
